function init(self)
	appsflyer_ad_revenue.initialize()
	appsflyer_ad_revenue.log_ad_revenue(
		"ironsource",
		appsflyer_ad_revenue.MN_GOOGLEADMOB,
		"USD",
		1.88,
		{
			[appsflyer_ad_revenue.PROP_COUNTRY] = "US",
			[appsflyer_ad_revenue.PROP_AD_UNIT] = "89b8c0159a50ebd1",
			[appsflyer_ad_revenue.PROP_AD_TYPE] = appsflyer_ad_revenue.AD_TYPE_INTERSTITIAL,
			[appsflyer_ad_revenue.PROP_PLACEMENT] = "place",
			[appsflyer_ad_revenue.PROP_ECPM_PAYLOAD] = "encrypt",
			["foo"] = "test1",
		})
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
